[package]
name = "projecteuler"
version = "0.1.0"
authors = ["Simon Auch <auchsimon@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "main"

[dependencies]
gcd = "2.*"